title: "Rust 1.70 で競プロ典型 90 問を解く"
summary: "AtCoder 採点システム 2023年版で使える Rust 1.70 で、競プロ典型 90 問 https://atcoder.jp/contests/typical90/ を解きます。\nアルゴリズムの考え方は公式解説などがありますので本記事では控えめにします。\nそれよりも、Rust でどのように実装するか、似た問題に対してどれだけ過去のコードを再利用できるかというところに焦点を当てます。\n問題を解きながら執筆中です。\n\n2024/01/20: 90問中 5問 公開"
topics: ["競技プログラミング", "rust"]
published: false
price: 0
chapters:
  - first
  - typical90_001
