title: "Rust 1.70 で競プロ典型 90 問を解く"
summary: "AtCoder 採点システム 2023年版で使える Rust 1.70 で、競プロ典型 90 問 https://atcoder.jp/contests/typical90/ を解きます。 アルゴリズムの考え方は公式解説などがありますので本記事では控えめにします。それよりも、Rust でどのように実装するか、似た問題に対してどれだけ過去のコードを再利用できるかというところに焦点を当てます。"
topics: ["競技プログラミング", "rust"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - first
  - typical90_001
