title: "Rust 1.70 で競プロ典型 90 問を解く"
summary: "AtCoder 採点システム 2023年版で使える Rust 1.70 で、競プロ典型 90 問 https://atcoder.jp/contests/typical90/ を解きます。\nアルゴリズムの考え方は公式解説などがありますので本記事では控えめにします。\nそれよりも、Rust でどのように実装するか、似た問題に対してどれだけ過去のコードを再利用できるかというところに焦点を当てます。\n問題を解きながら執筆中です。毎週日曜日に更新予定。\n\n2024/02/05: 4問追加。90問中 13問 公開"
topics: ["競技プログラミング", "rust"]
published: true
price: 0
chapters:
  - first
  - problems
  - typical90_001
  - typical90_002
  - typical90_003
  - typical90_004
  - typical90_005
  - typical90_006
  - typical90_007
  - typical90_008
  - typical90_009
  - typical90_010
  - typical90_011
  - typical90_012
  - typical90_013
